# Generated by Django 5.0.1 on 2024-01-08 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='DigitalRoad',
        #     fields=[
        #         ('record_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
        #         ('region', models.TextField(blank=True, db_column='Region', null=True)),
        #         ('county', models.TextField(blank=True, db_column='County', null=True)),
        #         ('sub_county', models.TextField(blank=True, db_column='Sub County', null=True)),
        #         ('name_of_site', models.TextField(blank=True, db_column='Name of Site', null=True)),
        #         ('dsh_category', models.TextField(blank=True, choices=[('publicwifi', 'Public Wifi'), ('lastmile', 'Last Mile'), ('backbone', 'Backbone')], db_column='DSH Category', null=True)),
        #         ('type_of_site', models.TextField(blank=True, db_column='Type of Site', null=True)),
        #         ('status', models.TextField(blank=True, choices=[('complete', 'Complete'), ('ongoing', 'Ongoing')], db_column='Status', default='ongoing', null=True)),
        #         ('no_of_aps', models.IntegerField(blank=True, db_column='No. of Aps', null=True)),
        #         ('date_surveyed', models.DateField(blank=True, db_column='Date Surveyed', null=True)),
        #         ('date_installed', models.DateField(auto_now_add=True, db_column='Date Installed', null=True)),
        #         ('contractor', models.TextField(blank=True, db_column='Contractor', null=True)),
        #         ('boq_amount', models.IntegerField(blank=True, db_column='BoQ Amount', null=True)),
        #         ('inspection_status', models.TextField(blank=True, db_column='Inspection status', null=True)),
        #         ('inspection_date', models.DateField(blank=True, db_column='Inspection Date', null=True)),
        #     ],
        #     options={
        #         'db_table': 'Digital-road',
        #         'managed': True,
        #     },
        # ),
    ]
